spring.data.mongodb.uri=mongodb://localhost:27017/developer_knowledge_vault
spring.data.mongodb.database=developer_knowledge_vault
server.port=8080

app.jwtSecret=9235b0c4a7a5140d88533e0abf7f2258550bccb6d5e93419712d3f88f71e8f2d
app.jwtExpirationInMs=86400000

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB